### ISSUE TITLE
Dataloader

### ISSUE THREAD

**Issue by leonlenk** [uclaacmai/text-decoder#1]
- the dataloader file should return a  dataloader based on a csv
- It should accept the path to an arbitrary csv  for the dataset (you can make assumptions about the format) so that members can use their own datasets
- We should also have a default dataset [probably this one](https://www.kaggle.com/datasets/usamabuttar/dad-jokes) 
- Make sure to have a parameter that allows it to easly take a subset of the data

**Comment by floatingtrees** [comment]
I can do this one
